// Dummy data for the Taglay Marketplace

export const products = [
  {
    id: "prod-001",
    name: "Sagada Arabica",
    category: "coffee",
    farmer: {
      name: "Juan dela Cruz",
      cooperative: "Sagada Farmers Cooperative",
      province: "Mountain Province",
    },
    pricePerKg: 850,
    minOrder: 25,
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&auto=format&fit=crop&q=60",
    isCertified: true,
    rating: 4.9,
    description: "High-altitude Arabica beans grown in the cool climate of Sagada. Notes of citrus, chocolate, and floral undertones.",
    origin: "Sagada, Mountain Province",
    harvestDate: "2024-11",
  },
  {
    id: "prod-002",
    name: "Benguet Highland Blend",
    category: "coffee",
    farmer: {
      name: "Maria Santos",
      cooperative: "Benguet Coffee Growers",
      province: "Benguet",
    },
    pricePerKg: 720,
    minOrder: 20,
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=60",
    isCertified: true,
    rating: 4.7,
    description: "A balanced blend from the highlands of Benguet. Medium body with hints of caramel and nuts.",
    origin: "La Trinidad, Benguet",
    harvestDate: "2024-10",
  },
  {
    id: "prod-003",
    name: "Davao Cacao Nibs",
    category: "cacao",
    farmer: {
      name: "Roberto Magsaysay",
      cooperative: "Davao Cacao Federation",
      province: "Davao del Sur",
    },
    pricePerKg: 480,
    minOrder: 50,
    image: "https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=800&auto=format&fit=crop&q=60",
    isCertified: true,
    rating: 4.8,
    description: "Premium cacao nibs from the volcanic soils of Davao. Rich, fruity flavor with low bitterness.",
    origin: "Davao City, Davao del Sur",
    harvestDate: "2024-09",
  },
  {
    id: "prod-004",
    name: "Batangas Liberica",
    category: "coffee",
    farmer: {
      name: "Pedro Rizal",
      cooperative: "Batangas Kapeng Barako Assoc.",
      province: "Batangas",
    },
    pricePerKg: 650,
    minOrder: 15,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=60",
    isCertified: true,
    rating: 4.6,
    description: "The legendary Kapeng Barako. Bold, strong, and aromatic with a distinctive smoky flavor.",
    origin: "Lipa, Batangas",
    harvestDate: "2024-11",
  },
  {
    id: "prod-005",
    name: "Ifugao Heirloom Weave",
    category: "textile",
    farmer: {
      name: "Rosa Dulnuan",
      cooperative: "Ifugao Weavers Guild",
      province: "Ifugao",
    },
    pricePerKg: 2500,
    minOrder: 5,
    image: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&auto=format&fit=crop&q=60",
    isCertified: true,
    rating: 5.0,
    description: "Hand-woven traditional textiles using centuries-old techniques. Natural dyes from local plants.",
    origin: "Banaue, Ifugao",
    harvestDate: "2024-08",
  },
  {
    id: "prod-006",
    name: "Sulu Black Pepper",
    category: "spice",
    farmer: {
      name: "Ahmad Hassan",
      cooperative: "Sulu Spice Traders",
      province: "Sulu",
    },
    pricePerKg: 380,
    minOrder: 10,
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&auto=format&fit=crop&q=60",
    isCertified: false,
    rating: 4.5,
    description: "Sun-dried black peppercorns with intense heat and complex flavor profile.",
    origin: "Jolo, Sulu",
    harvestDate: "2024-10",
  },
  {
    id: "prod-007",
    name: "Bukidnon Single Origin",
    category: "coffee",
    farmer: {
      name: "Carmen Lumad",
      cooperative: "Bukidnon Highlands Coop",
      province: "Bukidnon",
    },
    pricePerKg: 780,
    minOrder: 30,
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=60",
    isCertified: true,
    rating: 4.8,
    description: "Single-origin specialty coffee from the plateaus of Bukidnon. Sweet, clean, with berry notes.",
    origin: "Malaybalay, Bukidnon",
    harvestDate: "2024-11",
  },
  {
    id: "prod-008",
    name: "Palawan Wild Honey Cacao",
    category: "cacao",
    farmer: {
      name: "Elena Tagbanua",
      cooperative: "Palawan Indigenous Farmers",
      province: "Palawan",
    },
    pricePerKg: 520,
    minOrder: 25,
    image: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=800&auto=format&fit=crop&q=60",
    isCertified: true,
    rating: 4.9,
    description: "Organic cacao infused with wild forest honey. Unique flavor from pristine Palawan forests.",
    origin: "Puerto Princesa, Palawan",
    harvestDate: "2024-09",
  },
];

export const orders = [
  {
    id: "ORD-2024-001",
    productName: "Sagada Arabica",
    quantity: 50,
    totalPrice: 42500,
    status: "in-transit",
    logisticsStatus: "Departed Baguio Hub",
    origin: "Sagada, Mountain Province",
    destination: "Makati City, Metro Manila",
    estimatedDelivery: "2024-12-06",
    invoiceUrl: "/invoices/ORD-2024-001.pdf",
    createdAt: "2024-12-01",
  },
  {
    id: "ORD-2024-002",
    productName: "Davao Cacao Nibs",
    quantity: 100,
    totalPrice: 48000,
    status: "processing",
    logisticsStatus: "Preparing for Shipment",
    origin: "Davao City, Davao del Sur",
    destination: "BGC, Taguig",
    estimatedDelivery: "2024-12-10",
    invoiceUrl: "/invoices/ORD-2024-002.pdf",
    createdAt: "2024-12-02",
  },
  {
    id: "ORD-2024-003",
    productName: "Benguet Highland Blend",
    quantity: 30,
    totalPrice: 21600,
    status: "delivered",
    logisticsStatus: "Delivered",
    origin: "La Trinidad, Benguet",
    destination: "Quezon City, Metro Manila",
    estimatedDelivery: "2024-11-28",
    invoiceUrl: "/invoices/ORD-2024-003.pdf",
    createdAt: "2024-11-25",
  },
  {
    id: "ORD-2024-004",
    productName: "Ifugao Heirloom Weave",
    quantity: 10,
    totalPrice: 25000,
    status: "pending",
    logisticsStatus: "Awaiting Confirmation",
    origin: "Banaue, Ifugao",
    destination: "Alabang, Muntinlupa",
    estimatedDelivery: "2024-12-15",
    invoiceUrl: "/invoices/ORD-2024-004.pdf",
    createdAt: "2024-12-03",
  },
  {
    id: "ORD-2024-005",
    productName: "Bukidnon Single Origin",
    quantity: 75,
    totalPrice: 58500,
    status: "in-transit",
    logisticsStatus: "In Transit - Cagayan de Oro",
    origin: "Malaybalay, Bukidnon",
    destination: "Ortigas, Pasig",
    estimatedDelivery: "2024-12-08",
    invoiceUrl: "/invoices/ORD-2024-005.pdf",
    createdAt: "2024-12-01",
  },
];

// Partner logos for infinite scroll
export const partners = [
  { name: "Coffee Project", logo: "☕" },
  { name: "Auro Chocolate", logo: "🍫" },
  { name: "Commune Café", logo: "🌿" },
  { name: "Yardstick Coffee", logo: "📏" },
  { name: "The Curator", logo: "🎨" },
  { name: "Toby's Estate", logo: "🏠" },
  { name: "Single Origin", logo: "🌱" },
  { name: "Henry & Sons", logo: "👨‍👦" },
];
